[background]
path = "/home/urgobalt/pictures/wallpaper.png"
# Fill, Contain, Cover, or ScaleDown
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
font_name = "SourceCodePro Nerd Font"

[commands]
reboot = ["systemctl", "reboot"]
shutdown = ["systemctl", "poweroff"]

[appearance]
greeting_msg = "This is not Arch; You can't hack me."
